# Generated by Django 5.1.3 on 2026-04-03 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('technical', 'Technical Report'), ('verification', 'Verification Report'), ('research', 'Research Report')], max_length=30)),
                ('title', models.CharField(max_length=300)),
                ('author_name', models.CharField(max_length=200)),
                ('contributors', models.TextField(blank=True, help_text='Comma-separated contributor names')),
                ('abstract', models.TextField()),
                ('keywords', models.CharField(max_length=500)),
                ('plagiarism_doc', models.FileField(blank=True, null=True, upload_to='plagiarism/')),
                ('paper_doc', models.FileField(upload_to='papers/')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('revision_required', 'Revision Required'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='submitted', max_length=30)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('convener_notes', models.TextField(blank=True)),
                ('reviewer_feedback', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reports', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
